<time> ::= <twelve-hour> <am-pm> | <twelve-hour> <minutes-and-seconds> <am-pm> | <twelve-hour> <minutes> <am-pm> | <twelve-hour> <minutes> | <twenty-four-hour> <minutes-and-seconds> | <twenty-four-hour> <minutes>

<twelve-hour> ::= "12" | "1" | "01" | "2" | "02" | "3" | "03" | "4" | "04" | "5" | "05" | "6" | "06" | "7" | "07" | "8" | "08" | "9" | "09" | "10" | "11"

<am-pm> ::= "AM" | "am" | "PM" | "pm"

<twenty-four-hour> ::= "00" | "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19" | "20" | "21" | "22" | "23"

<minutes-and-seconds> ::= <minutes-or-seconds> <minutes-or-seconds>

<minutes> ::= <minutes-or-seconds>

<minutes-or-seconds> ::= ":" <zero-to-fifty-nine>

<zero-to-fifty-nine> ::= <zero-to-five> <zero-to-nine>

<zero-to-five> ::= "0" | "1" | "2" | "3" | "4" | "5"

<zero-to-nine> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
